// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ykzUd4oAym2NYgT6Y50fSjkLU3N2uPs',
    appId: '1:724807825578:web:9eee06fe2cf6a56f58b8d3',
    messagingSenderId: '724807825578',
    projectId: 'tamate-be',
    authDomain: 'tamate-be.firebaseapp.com',
    storageBucket: 'tamate-be.firebasestorage.app',
    measurementId: 'G-SY48KWT2WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATozEldJbUfgHffU8-ZTKdySqgAvXOpaI',
    appId: '1:724807825578:android:d7b1633eae9a7bde58b8d3',
    messagingSenderId: '724807825578',
    projectId: 'tamate-be',
    storageBucket: 'tamate-be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlTsj3whTtaeoBVM69r6L-1W3UWJx34i4',
    appId: '1:724807825578:ios:53c3e0ce48ddd4c758b8d3',
    messagingSenderId: '724807825578',
    projectId: 'tamate-be',
    storageBucket: 'tamate-be.firebasestorage.app',
    iosClientId: '724807825578-1pr52sjmt8c15q714emh0lo0hrqd56ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlTsj3whTtaeoBVM69r6L-1W3UWJx34i4',
    appId: '1:724807825578:ios:53c3e0ce48ddd4c758b8d3',
    messagingSenderId: '724807825578',
    projectId: 'tamate-be',
    storageBucket: 'tamate-be.firebasestorage.app',
    iosClientId: '724807825578-1pr52sjmt8c15q714emh0lo0hrqd56ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1ykzUd4oAym2NYgT6Y50fSjkLU3N2uPs',
    appId: '1:724807825578:web:9a28e14e407c99ba58b8d3',
    messagingSenderId: '724807825578',
    projectId: 'tamate-be',
    authDomain: 'tamate-be.firebaseapp.com',
    storageBucket: 'tamate-be.firebasestorage.app',
    measurementId: 'G-0M84WPY8FN',
  );

}
